### ISSUE TITLE
Arguments are not saved in the logs

### ISSUE THREAD

**Issue by edudev** [VaniOFX/DQN-divergence#2]
@AmanDaVinci Not sure if it's an issue with my environment, but I don't see the config args in the logs.

**Comment by edudev** [comment]
Okay, so I saw that it creates .yml files on the fly, which is great. Though it took me a while to figure out how to configure it from the command line.
Anyway, we do have the config for each run.

Can we also have all the Q-values? I believe we talked that it'd be great for making plots afterwards.

**Comment by AmanDaVinci** [comment]
Hey sorry for replying late. But yeah they are saved in the experiments/.hydra/config.yaml file.
I have not yet pushed the code for tracking and recording all the values during training. I was doing it with tensorboard but then some of the data types are strings (like actions taken), so I have opted to simply save them in a CSV file which can be later used to analyze/plot in a notebook using pandas and matplotlib.

**Comment by edudev** [comment]
CSV sounds good. Though why are some actions strings? We have a fixed action space, so all actions should be numbered from 0 to n.

**Comment by AmanDaVinci** [comment]
Oh sorry, not strings. I meant not single numbers like states. It doesn't make sense to plot them on tensorboard.

**Comment by VaniOFX** [comment]
Implemented and merged. Closing.
